package:
  name: libyaml
  version: 0.2.1

source:
  url: https://github.com/yaml/libyaml/archive/0.2.1.zip

build:
  library: true
  script: |
    emcmake cmake -DCMAKE_INSTALL_PREFIX=.. .
    emmake make -j ${PYODIDE_JOBS:-3}
    ln -s /src/packages/libyaml/build/libyaml-0.2.1/libyaml_static.a /src/packages/libyaml/build/libyaml.a
    ln -s /src/packages/libyaml/build/libyaml-0.2.1/include /src/packages/libyaml/build/
